baseURL: https://marekko.github.io/
languageCode: en-us
title: Marek Konieczny Homepage
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marek Konieczny Personal Site
  description: "ExampleSite description"
  keywords: [Blog, Portfolio]
  author: Marek Konieczny
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "marekko"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    subtitle: "I am a Researcher of Computer Science at AGH-UST University, Krakow, Poland. I work on computer networks, distributed systems, cloud computing, and serverless computing. I am the Central Point of Contact for AWS Academy at AGH-UST."
    author: Marek Konieczny
    title: Personal site
    #    subtitle: "This is subtitle"
    imageUrl: "/mk.png"
    imageWidth: 150
    imageHeight: 170
    imageTitle: my image
    buttons:
      - name: papers
        url: papers
      - name: aws
        url: aws
      - name: courses
        url: courses


  socialIcons:
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=jqjzh_sAAAAJ"
    - name: email
      url: "https://skos.agh.edu.pl/osoba/marek-konieczny-8480.html"
      #    - name: webex
      #      url: "https://agh-mche.webex.com/meet/marekko"
    - name: github
      url: "https://github.com/marekko"

  analytics:
    google:
      SiteVerificationTag: "UA-43049307-1"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  
menu:
  main:
    - identifier: papers
      name: Papers
      url: /papers/
      weight: 1
    - identifier: aws
      name: AWS Knols
      url: /aws/
      weight: 2
    - identifier: courses
      name: Courses
      url: /courses/
      weight: 3
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    #
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
